@startuml
class Chat {
    + Name : string? <<get>> <<set>>
    + Lastmessage : string? <<get>> <<set>>
    + ChatAdministrator : Guid? <<get>> <<set>>
}
class "ICollection`1"<T> {
}
Chat --> "Id" Guid
Chat o-> "Messages<ChatMessage>" "ICollection`1"
Chat o-> "ChatUsers<ChatUser>" "ICollection`1"
@enduml
