@startuml
class AppDbContext {
    + AppDbContext(options:DbContextOptions<AppDbContext>)
}
class "DbSet`1"<T> {
}
DbContext <|-- AppDbContext
AppDbContext --> "Users<AppUser>" "DbSet`1"
AppDbContext --> "ProfileImageClaims<ProfileImageClaims>" "DbSet`1"
AppDbContext --> "ProfileImages<UserProfileImage>" "DbSet`1"
AppDbContext --> "ProfileImageStorages<UserProfileImageStorage>" "DbSet`1"
AppDbContext --> "Messages<ChatMessage>" "DbSet`1"
AppDbContext --> "Chats<Chat>" "DbSet`1"
AppDbContext --> "ChatUsers<ChatUser>" "DbSet`1"
@enduml
