@startuml
class AppUser {
    + Username : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PasswordHash : byte[]? <<get>> <<set>>
    + PasswordSalt : byte[]? <<get>> <<set>>
    + RefreshToken : string <<get>> <<set>>
    + CurrentImageBytes : byte[]? <<get>> <<set>>
}
class "ICollection`1"<T> {
}
AppUser --> "Id" Guid
AppUser --> "TokenCreated" DateTime
AppUser --> "TokenExpires" DateTime
AppUser --> "AccountCreated" DateTime
AppUser --> "AccountLastTimeEdited" DateTime
AppUser --> "LastTimeOnline" DateTime
AppUser o-> "UserProfileImages<UserProfileImage>" "ICollection`1"
AppUser o-> "SentMessages<ChatMessage>" "ICollection`1"
AppUser o-> "ReceivedMessages<ChatMessage>" "ICollection`1"
@enduml
